Feature/ts
Vylpes/vylbot-core pull request #42
Opened 2021-07-14 13:56 UTC by Vylpes

2021-07-16 19:54 UTC, Vylpes commented
Need to fix events, I'm unable right now to pass variables into the execution method since you can't have variables be different depending on the event if you use an overwrite method.

2021-07-18 14:29 UTC, Vylpes commented
Should hopefully be fixed now

2021-07-18 18:48 UTC, VylpesTester requested changes

2021-07-18 18:48 UTC, VylpesTester commented on .env.template
> +# Security Warning! Do not commit this file to any VCS!
Document this file

2021-07-18 18:48 UTC, VylpesTester commented on src/client/client.ts
> +        super.on("ready", this._events.onReady);
This should also be an event in the event class

2021-07-18 18:48 UTC, VylpesTester commented on src/client/events.ts
> +            valid: true,
Should be false?

2021-07-18 18:48 UTC, VylpesTester commented on src/client/util.ts
> +            message: "Member is not part of member",
"Member is not part of message"

2021-07-24 11:57 UTC, VylpesTester approved these changes

2021-07-24 11:57 UTC, merged